<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-21T12:43:18 IST" name="Suite" finished-at="2025-05-21T12:43:55 IST" duration-ms="36759">
    <groups>
      <group name="Master">
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@dbd8e44]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@25aca718]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@2250b9f2]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@5dcd8c7a]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@142269f2]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@253d9f73]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
      </group> <!-- Master -->
      <group name="Sanity">
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@dbd8e44]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@2250b9f2]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
        <method signature="TC0001_accountRegistration.Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@142269f2]" name="Verify_Account_Registration" class="testCase.TC0001_accountRegistration"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@25aca718]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@5dcd8c7a]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
        <method signature="TC0002_accountLogin.verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@253d9f73]" name="verifyLogin" class="testCase.TC0002_accountLogin"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2025-05-21T12:43:18 IST" name="Edge" finished-at="2025-05-21T12:43:55 IST" duration-ms="36759">
      <class name="testCase.TC0001_accountRegistration">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testCase.TC0001_accountRegistration@2250b9f2]" started-at="2025-05-21T12:43:36 IST" name="setup" finished-at="2025-05-21T12:43:43 IST" duration-ms="7462" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Window]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Verify_Account_Registration()[pri:0, instance:testCase.TC0001_accountRegistration@2250b9f2]" started-at="2025-05-21T12:43:43 IST" name="Verify_Account_Registration" finished-at="2025-05-21T12:43:53 IST" duration-ms="10246" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCase.TC0001_accountRegistration.Verify_Account_Registration(TC0001_accountRegistration.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Account_Registration -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCase.TC0001_accountRegistration@2250b9f2]" started-at="2025-05-21T12:43:53 IST" name="teardown" finished-at="2025-05-21T12:43:55 IST" duration-ms="1256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCase.TC0001_accountRegistration -->
      <class name="testCase.TC0002_accountLogin">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testCase.TC0002_accountLogin@5dcd8c7a]" started-at="2025-05-21T12:43:18 IST" name="setup" finished-at="2025-05-21T12:43:28 IST" duration-ms="9779" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Window]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogin()[pri:0, instance:testCase.TC0002_accountLogin@5dcd8c7a]" started-at="2025-05-21T12:43:28 IST" name="verifyLogin" finished-at="2025-05-21T12:43:32 IST" duration-ms="3543" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCase.TC0002_accountLogin.verifyLogin(TC0002_accountLogin.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCase.TC0002_accountLogin@5dcd8c7a]" started-at="2025-05-21T12:43:32 IST" name="teardown" finished-at="2025-05-21T12:43:36 IST" duration-ms="3244" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Timed out waiting for driver server to stop.
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [3f3d55a2-af40-4ddc-bbf3-de66a0270fcd, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.4, moz:accessibilityChecks: false, moz:buildID: 20250517143237, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 14480, moz:profile: C:\Users\Admin\AppData\Loca..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Timed out waiting for driver server to stop.
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [3f3d55a2-af40-4ddc-bbf3-de66a0270fcd, quit {}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.4, moz:accessibilityChecks: false, moz:buildID: 20250517143237, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 14480, moz:profile: C:\Users\Admin\AppData\Loca..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:164)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:446)
at org.openqa.selenium.firefox.FirefoxDriver.quit(FirefoxDriver.java:302)
at testBase.baseClass.teardown(baseClass.java:100)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@44dd5d99[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@fb91e5b[Wrapped task = org.openqa.selenium.remote.http.jdk.JdkHttpClient$$Lambda/0x00000116102abab0@4abb91c8]] rejected from java.util.concurrent.ThreadPoolExecutor@27b80d99[Shutting down, pool size = 3, active threads = 2, queued tasks = 0, completed tasks = 100]
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:160)
... 25 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@44dd5d99[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@fb91e5b[Wrapped task = org.openqa.selenium.remote.http.jdk.JdkHttpClient$$Lambda/0x00000116102abab0@4abb91c8]] rejected from java.util.concurrent.ThreadPoolExecutor@27b80d99[Shutting down, pool size = 3, active threads = 2, queued tasks = 0, completed tasks = 100]
at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.executeAsync(JdkHttpClient.java:384)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:413)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:212)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.lambda$execute$1(DriverCommandExecutor.java:126)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
... 3 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCase.TC0002_accountLogin -->
    </test> <!-- Edge -->
  </suite> <!-- Suite -->
</testng-results>
